<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;netstandard2.0;netstandard2.1;net8.0;net9.0;net10.0</TargetFrameworks>
    <OutputType>Library</OutputType>
    <RootNamespace>Microsoft.Extensions.Caching</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <SignAssembly>True</SignAssembly>
  </PropertyGroup>

  <!--NuGet package-->
  <PropertyGroup>
    <Product>HttpClient.Caching</Product>
    <Description>HTTP response caching for HttpClient.</Description>
    <Version>1.0.0</Version>
    <Authors>Thomas Galliker</Authors>
    <PackageId>HttpClient.Caching</PackageId>
    <PackageTags>retry;resilience;resilient;fault;failure;http;handler;HttpRetryHelper;ApiClient;ApiService</PackageTags>
    <PackageIcon>logo.png</PackageIcon>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/thomasgalliker/HttpClient.Caching</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/thomasgalliker/HttpClient.Caching</RepositoryUrl>
    <Company>superdev GmbH</Company>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Copyright>Copyright $([System.DateTime]::Now.ToString(`yyyy`)) © Thomas Galliker</Copyright>
    <PackageReleaseNotes>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)/../ReleaseNotes.txt"))</PackageReleaseNotes>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedAllSources>true</EmbedAllSources>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="True" PackagePath="\" />
    <None Include="..\LICENSE" Pack="True" PackagePath="\" />
    <None Include="..\logo.png" Pack="True" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Reference Include="System.Net.Http" />
  </ItemGroup>
</Project>
